---
title: "Publications"
---

## 2025

[Bacteriophage-driven DNA inversions shape bacterial functionality and long-term co-existence in *Bacteroides fragilis*](https://doi.org/10.1080/19490976.2025.2501492)*, Gut Microbes* (2025)\
[#Carasso S]{.underline}, #Keshet-David R, Zhang J, Hajjo H, Kadosh-Kariti D, Gefen T, Geva-Zatorsky N

[Dietary carbohydrates alter immune-modulatory functionalities and DNA inversions in *Bacteroides thetaiotaomicron*](https://doi.org/10.1038/s41467-025-60202-9)*, Nature Communications* (2025)\
Gal-Mandelbaum N, [Carasso S]{.underline}, Kedem A, Ziv T, Keshet-David R, Abboud R, Zaatry R, Gefen T, Geva-Zatorsky N

[Esophageal microbiome correlates with post-esophagectomy anastomotic leak in cancer patients](https://doi.org/10.1016/j.esmogo.2025.100172), *ESMO Gastrointestinal Oncology* (2025)\
#Naddaf R, #Shmilovich H, [#Carasso S]{.underline}, Keshet-David R, Herren R, Gefen T, Goshen-Lago T, Zwang Y, Livyatan I, Shental N, Haberfeld O, Straussman R, Markar S.R., Nilsson M, Kashtan H, Ben-Aharon I, Geva-Zatorsky N

[Efficiency and outcomes in microvascular anastomosis: A meta-analysis of mechanical versus manual techniques](https://doi.org/10.1016/j.jcms.2025.07.015), *Journal of Cranio-Maxillofacial Surgery* (2025)\
Ohayon C, Gross N, Capucha T, [Carasso S]{.underline}, Fichter AM, Rachmiel A, Emodi O

[The never-ending story: single versus dual venous anastomoses in microsurgical radial forearm free flap for head and neck reconstruction. A meta-analysis](#0), *Journal of Cranio-Maxillofacial Surgery* (2025)\
Ohayon C, Ritschl LM, Capucha T, [Carasso S]{.underline}, Shkedy Y, Rachmiel A, Wolff K-D, Emodi O

## 2024

[Inflammation and bacteriophages affect DNA inversion states and functionality of the gut microbiota](https://doi.org/10.1016/j.chom.2024.02.003), *Cell Host & Microbe* (2024)\
[#Carasso S]{.underline}, #Zaatry R, #Hajjo H, #Kadosh-Kariti D, Ben-Assa N, Naddaf N, Mandelbaum N, Pressman S, Chowers Y, Gefen T, Jeffrey K.L., Jofre J, Coyne M.J., Comstock L.E., Sharon I, Geva-Zatorsky N

## 2023

[Gut microbial signatures are associated with Lynch syndrome (LS) and cancer history in Druze communities in Israel](https://doi.org/10.1038/s41598-023-47723-3), *Scientific Reports* (2023)\
#Naddaf R, [#Carasso S]{.underline}, Reznick-Levi G, Hasnis E, Qarawani A, Maza I, Gefen T, Half E. E., Geva-Zatorsky N

[Extracellular vesicles of the Gram-positive gut symbiont \*Bifidobacterium longum\* induce immune-modulatory, anti-inflammatory effects](https://doi.org/10.1038/s41522-023-00400-9), *npj Biofilms and Microbiomes* (2023)\
Mandelbaum N, Zhang L, [Carasso S]{.underline}, Ziv T, Lifshiz-Simon S, Davidovich I, Luz I, Berinstein E, Gefen T, Cooks T, Talmon Y, Balskus E. P., Geva-Zatorsky N

## 2022

[Microbiome characterization of infected diabetic foot ulcers in association with clinical outcomes: traditional cultures versus molecular sequencing methods](https://doi.org/10.3389/fcimb.2022.836699), *Front. Cell. Infect. Microbiol* (2022)\
#Mudrik-Zohar H, [#Carasso S]{.underline}, Gefen T, Zalmanovich A, Katzir M, Cohen Y, Paitan Y, Geva-Zatorsky N, Chowers M

## 2021

[The mechanical cost of decreasing conduction velocity: a mathematical model of pacing-induced lower strain](https://doi.org/10.4022%2Fjafib.20200444), *J Atr Fibrillation* (2021)\
Marai I, Carasso D, [Carasso S]{.underline}, Carasso S

[Metagenomic analysis reveals the signature of gut microbiota associated with human chronotypes](https://faseb.onlinelibrary.wiley.com/doi/10.1096/fj.202100857RR), *FASEB J* (2021)\
[Carasso S]{.underline}, Fishman B, Lask LS, Shochat T, Geva-Zatorsky N, Tauber E

["More guts than brains?"--the role of gut microbiota in idiopathic intracranial hypertension](https://doi.org/10.1097/wno.0000000000001330), *Journal of Neuro-Ophthalmology* (2021)\
Berkowitz E, Kopelman Y, Kadosh D, [Carasso S]{.underline}, Tiosano B, Kesler A, Geva-Zatorsky N

## 2020

[Analysis of a phase-variable restriction modification system of the human gut symbiont \*Bacteroides fragilis](https://doi.org/10.1093/nar/gkaa824), *Nucleic Acids Research* (2020)\
Ben-Assa N, Coyne MJ, Fomenkov A, Livny J, Robins WP, Muniesa M, Carey V, [Carasso S]{.underline}, Gefen T, Jofre J, Roberts RJ, Comstock LE, Geva-Zatorsky N

[Oral capsulized fecal microbiota transplantation for eradication of carbapenemase-producing Enterobacteriaceae colonization with a metagenomic perspective](https://doi.org/10.1093/cid/ciaa737), *Clinical Infectious Diseases* (2020)\
#Bar-Yoseph H, [#Carasso S]{.underline}, Shklar S, Korytny A, Even Dar R, Daoud H, Nassar R, Maharshak N, Hussein K, Geffen Y, Chowers Y, Geva-Zatorsky N, Paul M

[Phage-Bacteria Associations: Analyze. Match. Develop Therapies](https://doi.org/10.1016/j.chom.2020.08.009), *Cell Host & Microbe* (2020)\
[Carasso S]{.underline}, Hajjo H, Geva-Zatorsky N
